import type { Metadata } from "next";
import "./globals.css";
import { PageTitleProvider } from './context/PageTitleContext';
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <PageTitleProvider>
      <div className="bg-gray-50 text-gray-900 font-sans min-h-screen">
        <Header />
        <main className="max-w-7xl mx-auto px-4 py-6">{children}</main>
      </div>
    </PageTitleProvider>
    </body>
    </html>
  );
}
